title: Angela Cox Portfolio
description: "Angela Cox Portfolio"

# Leave URL blank to listen on all addresses
url: "https://angportfolio.aerobatic.io"
baseurl: ""

# Social
#twitter:
#facebook:
github: AngelaCox
linkedin: angela-cox-27096540

nav_title: Angela Cox
nav_position: Technical Writer
nav_image: avatar.png
# Links to the Download CV button
cv: CVACoxApril2016.pdf

# Analytics
google_analytics: UA-75745958-1

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      collections: projects
    values:
      layout: project

collections:
  projects:
    output: true

exclude: ["README.md", "package.json"]
