title: Angela Cox Portfolio
description: "Angela Cox Portfolio"

# Leave URL blank to listen on all addresses
url: "http://angportfolio.aerobatic.io"
baseurl: ""

# Social
#twitter:
#facebook:
github: AngelaCox
linkedin: angela-cox-27096540

nav_title: Angela Cox
nav_position: Technical Writer
# Links to the Download CV button
cv: CVACoxMar2016.pdf

# Analytics


# Build settings
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      collections: projects
    values:
      layout: project

collections:
  projects:
    output: true

exclude: ["package.json"]
